// modules/material.js
export const UPDATE_QUANTITY = 'UPDATE_QUANTITY';
export const UPDATE_UNIT = 'UPDATE_UNIT';
export const UPDATE_NOTE = 'UPDATE_NOTE';
export const DELETE_MATERIAL = 'DELETE_MATERIAL';
export const SAVE_MATERIAL = 'SAVE_MATERIAL';
export const CHANGE_FILENAME = 'CHANGE_FILENAME';

// modules/labels.js
export const SET_DEFAULT_CATELOG = 'SET_DEFAULT_CATELOG';
export const SET_SELECTED_INDEX = 'SET_SELECTED_INDEX';
export const SET_SELECTED_MAIN_CATELOG = 'SET_SELECTED_MAIN_CATELOG';
export const ADD_SECOND_CATELOG = 'ADD_SECOND_CATELOG';
export const ADD_MAIN_CATELOG = 'ADD_MAIN_CATELOG';
export const ADD_LABEL = 'ADD_LABEL';
export const EDIT_CATEGORY = 'EDIT_CATEGORY';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';

// index.js
export const SET_IS_LOADING = 'SET_IS_LOADING';
